// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAubgWIyh5GS1gX6yrxsdvL2C3rATHtXbU',
    appId: '1:752567322079:android:9927beb91a845e9dd2706a',
    messagingSenderId: '752567322079',
    projectId: 'fitconnect-2ba3f',
    storageBucket: 'fitconnect-2ba3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxMxI3-RFG2YZu_7mS_i7q_WktxdGm8pE',
    appId: '1:752567322079:ios:bdbc8f9baf4a4b6ad2706a',
    messagingSenderId: '752567322079',
    projectId: 'fitconnect-2ba3f',
    storageBucket: 'fitconnect-2ba3f.firebasestorage.app',
    androidClientId: '752567322079-ifipsc0ra784pgcqk5kgohbpred2pepk.apps.googleusercontent.com',
    iosClientId: '752567322079-ea5787am04bvg5h9viujltha92i8mv0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitconnect',
  );

}